### ISSUE TITLE
Post /productos "error al crear producto"

### ISSUE THREAD

**Issue by jmendoza20** [Equipo1-7K/VentasCatalogo#10]
Al crear un cliente si se pone en la variable "noInterno" como respuesta "no tiene", arroja un error 500 el servidor.

Cuerpo de la solicitud:
```json
{
  "nombre": "iphone xs 64gb",
  "descripcion": "Nuevo Iphone xs con capacidad de 64gb, ios 12, nueva pantalla true retina de 5.8 pulgadas, cámara con flash true tone ",
  "precio": "23499"
}
```
Cuerpo de la respuesta:
```json
[
  {
    "trace": [
      {
        "stepName": "Producto_Agregar_Req"
      },
      {
        "stepName": "precio"
      }
    ],
    "errorType": 2,
    "typeIs": "string",
    "typeShouldBe": "number"
  }
]
```

**Comment by fxbi-dev** [comment]
Esta descripción no coincide con el servicio que se reporta
> Al crear un cliente si se pone en la variable "noInterno" como respuesta "no tiene", arroja un error 500 el servidor.

Como el mensaje dice, lo que se espera es un número, no una cadena, lo que se está enviando es una cadena
> `"precio": "23499"`

Debería ser
```json
{
  "nombre": "iphone xs 64gb",
  "descripcion": "Nuevo Iphone xs con capacidad de 64gb, ios 12, nueva pantalla true retina de 5.8 pulgadas, cámara con flash true tone ",
  "precio": 23499
}
```
