### ISSUE TITLE
Get /ventas "error al obtener ventas paginadas"

### ISSUE THREAD

**Issue by jmendoza20** [Equipo1-7K/VentasCatalogo#11]
Al solicitar la pagina de las ventas correspondientes al usuario salta error 500 del servidor.

Cuerpo de la solicitud:
```json
"page": 1
"perPage": 15
```
Cuerpo de la respuesta:
```json
{
    "message": "Algo salió mal :C"
}
```

**Comment by fxbi-dev** [comment]
Esto se debe a un problema en el servidor de base de datos, se corrige cambiando una configuración que se modifica en cada arranque del servidor.

La solución está en el deploy, hay que revisar que ya funcione bien.

**Comment by jmendoza20** [comment]
arreglado error en la base de datos, por lo cual ya funciona
