### ISSUE TITLE
Post /ventas "error al crear venta, se ejecuta, pero no coincide con documentacion"

### ISSUE THREAD

**Issue by jmendoza20** [Equipo1-7K/VentasCatalogo#12]
Al crear una venta, no se despliegan los datos completos en la respuesta, sin embargo si se guardan, ya que aparecen al utilizar Get /ventas/{id} 

Cuerpo de la solicitud:
```json
{
  "idCliente": 4,
  "pago": {
    "tipo": "Credito",
    "acuerdo": "parcialidades",
    "cantidad": 15,
    "intervaloPago": 15,
    "fechaPrimerPago": "2018-12-25"
  },
  "productos": [
    {
      "idProducto": 3,
      "cantidad": 2
    }
  ]
}
```
Cuerpo de la respuesta:
```json
{
  "id": 3,
  "idCliente": 4,
  "pago": {}
}
```
Cuerpo de la documentación:
```json
{
  "id": 0,
  "idCliente": 0,
  "cantProductos": 0,
  "total": 0,
  "abono": {
    "total": 0,
    "deuda": 0
  },
  "status": "Sin Pago",
  "pago": {
    "tipo": "Credito",
    "acuerdo": "Parcialidades",
    "cantidad": 0,
    "fechaPrimerPago": "string",
    "intervaloPago": 0
  }
}
```

**Comment by fxbi-dev** [comment]
El problema era la función que se encarga de darle formato a una respuesta de una vista para que aparezca como en la documentación. Igualmente, en la documentación faltaban un par de datos

El issue se corrige en el pull request #20

**Comment by jmendoza20** [comment]
el error fue corregido
