### ISSUE TITLE
Post /venta "error en validación de mayúsculas"

### ISSUE THREAD

**Issue by jmendoza20** [Equipo1-7K/VentasCatalogo#14]
Al crear una venta, en caso de escribir alguna opción en minúsculas genera un error en los abonos generados en donde se toma la variable "cantidad" como la cantidad de dinero que se debe de abonar cada parcialidad

Cuerpo de la solicitud:
```json
{
  "idCliente": 4,
  "pago": {
    "tipo": "Credito",
    "acuerdo": "parcialidades",
    "cantidad": 15,
    "intervaloPago": 15,
    "fechaPrimerPago": "2018-12-25"
  },
  "productos": [
    {
      "idProducto": 3,
      "cantidad": 2
    }
  ]
}
```
Cuerpo de la respuesta:
```json
{
  "id": 3,
  "idCliente": 4,
  "pago": {}
}
```
Cuerpo de la documentación:
```json
{
  "id": 0,
  "idCliente": 0,
  "cantProductos": 0,
  "total": 0,
  "abono": {
    "total": 0,
    "deuda": 0
  },
  "status": "Sin Pago",
  "pago": {
    "tipo": "Credito",
    "acuerdo": "Parcialidades",
    "cantidad": 0,
    "fechaPrimerPago": "string",
    "intervaloPago": 0
  }
}
```

**Comment by fxbi-dev** [comment]
Este era un problema similar al issue #8.
Se resuelve, de igual manera, con el pull request #16

**Comment by jmendoza20** [comment]
no permite registrar con minuscula al principio "Parcialidades" o "Dinero", el error fue arreglado
