### ISSUE TITLE
Post /clientes "error en variable noInterno"

### ISSUE THREAD

**Issue by jmendoza20** [Equipo1-7K/VentasCatalogo#8]
Al crear un cliente si se pone en la variable "noInterno" como respuesta "no tiene", arroja un error 500 el servidor.

Cuerpo de la solicitud:
```json
{
  "nombre": "Juan",
  "apPaterno": "Hernandez",
  "apMaterno": "Gutierrez",
  "domicilio": {
    "estado": "Colima",
    "municipio": "Colima",
    "cp": "28000",
    "colonia": "Centro",
    "calle": "Madero",
    "noExterno": "201",
    "noInterno": "",
    "referencia": "esta al lado de un kiosko"
  }
}
```
Cuerpo de la respuesta:
```json
{
    "message": "Algo salió mal :C"
}
```

**Comment by fxbi-dev** [comment]
Era un problema de la documentación, no estaba asignada la propiedad `maxLenght` en ningúna definición, esto debería resolver el problema. La solución está en progreso

**Comment by fxbi-dev** [comment]
El merge request que resuelve esto es el #16

**Comment by jmendoza20** [comment]
Teniendo max lenght ya no permite la entrada de "no tiene" en ese campo, generando un error 40X en lugar de 50X a la hora de intentarlo,
