### ISSUE TITLE
Put /clientes/{id}/domicilio "error en la petición de cambio de domicilio"

### ISSUE THREAD

**Issue by jmendoza20** [Equipo1-7K/VentasCatalogo#9]
Al tratar de cambiar el domicilio de un cliente arroja un error 500 el servidor, el problema no reside en las variables.

Cuerpo de la solicitud original:
```json
{
  "estado": "Colima",
  "municipio": "Colima",
  "cp": "28000",
  "colonia": "Centro",
  "calle": "vicente guerrero",
  "noExterno": "76",
  "noInterno": "",
  "referencia": "al lado del oxxo"
}
```
Cuerpo de la solicitud consiguiente:
```json
{
  "estado": "Colima",
  "municipio": "Colima",
  "cp": "28000",
  "colonia": "Centro",
  "calle": "guerrero",
  "noExterno": "76",
  "noInterno": "",
  "referencia": "al lado del oxxo"
}
```
Cuerpo de la respuesta:
```json
{
    "message": "Algo salió mal :C"
}
```

**Comment by fxbi-dev** [comment]
Este bug se debía a una falla en la consulta que se encarga de esta acción, la corrección está en el pull request #18

**Comment by jmendoza20** [comment]
El domicilio es guardado de forma correcta despues de los cambios
